// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpJCKN2V8jFntW5LOIEx-Rl-EiJIHcEGk',
    appId: '1:132625858105:web:571b1a36bdeb53c12057e8',
    messagingSenderId: '132625858105',
    projectId: 'mukhlis-bb51b',
    authDomain: 'mukhlis-bb51b.firebaseapp.com',
    storageBucket: 'mukhlis-bb51b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHf0OB6zbmLoa7QWo67GpgGJF_xh9Lky8',
    appId: '1:132625858105:android:c97448d58821d3d62057e8',
    messagingSenderId: '132625858105',
    projectId: 'mukhlis-bb51b',
    storageBucket: 'mukhlis-bb51b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUbyfz-0UYl617lKlzGGkLOGIe6lkO3eU',
    appId: '1:132625858105:ios:6cb3e4f3992d33852057e8',
    messagingSenderId: '132625858105',
    projectId: 'mukhlis-bb51b',
    storageBucket: 'mukhlis-bb51b.firebasestorage.app',
    iosBundleId: 'com.example.mukhliss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUbyfz-0UYl617lKlzGGkLOGIe6lkO3eU',
    appId: '1:132625858105:ios:6cb3e4f3992d33852057e8',
    messagingSenderId: '132625858105',
    projectId: 'mukhlis-bb51b',
    storageBucket: 'mukhlis-bb51b.firebasestorage.app',
    iosBundleId: 'com.example.mukhliss',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpJCKN2V8jFntW5LOIEx-Rl-EiJIHcEGk',
    appId: '1:132625858105:web:f1c3063bd52aba6d2057e8',
    messagingSenderId: '132625858105',
    projectId: 'mukhlis-bb51b',
    authDomain: 'mukhlis-bb51b.firebaseapp.com',
    storageBucket: 'mukhlis-bb51b.firebasestorage.app',
  );
}
